MODEL_NAME = "yolov8n.pt"
MODEL_RESOLUTION = 1280

CONFIDENCE_THRESHOLD = 0.3
IOU_THRESHOLD = 0.7

PIXELS_PER_METER = 20
SPEED_MIN = 3
SPEED_MAX = 140

TRACE_SECONDS = 2
WINDOW_SECONDS = 0.5
MAX_PIXEL_JUMP = 25
